// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssm.proto

package org.colorfuldays.ssm.domain.protobuf;

public final class Ssm {
  private Ssm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string password = 3;
    boolean hasPassword();
    String getPassword();
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(Builder builder) {
      super(builder);
    }
    private User(boolean noInit) {}
    
    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.colorfuldays.ssm.domain.protobuf.Ssm.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.colorfuldays.ssm.domain.protobuf.Ssm.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable;
      }
      
      // Construct using org.colorfuldays.ssm.domain.protobuf.Ssm.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.User.getDescriptor();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.User getDefaultInstanceForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.User.getDefaultInstance();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.User build() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.colorfuldays.ssm.domain.protobuf.Ssm.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.colorfuldays.ssm.domain.protobuf.Ssm.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.User buildPartial() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.User result = new org.colorfuldays.ssm.domain.protobuf.Ssm.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.colorfuldays.ssm.domain.protobuf.Ssm.User) {
          return mergeFrom((org.colorfuldays.ssm.domain.protobuf.Ssm.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.colorfuldays.ssm.domain.protobuf.Ssm.User other) {
        if (other == org.colorfuldays.ssm.domain.protobuf.Ssm.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string password = 3;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.colorfuldays.ssm.domain.protobuf.User)
    }
    
    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.colorfuldays.ssm.domain.protobuf.User)
  }
  
  public interface BookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string isbn = 3;
    boolean hasIsbn();
    String getIsbn();
    
    // repeated string author = 4;
    java.util.List<String> getAuthorList();
    int getAuthorCount();
    String getAuthor(int index);
    
    // optional int64 publish_date = 5;
    boolean hasPublishDate();
    long getPublishDate();
  }
  public static final class Book extends
      com.google.protobuf.GeneratedMessage
      implements BookOrBuilder {
    // Use Book.newBuilder() to construct.
    private Book(Builder builder) {
      super(builder);
    }
    private Book(boolean noInit) {}
    
    private static final Book defaultInstance;
    public static Book getDefaultInstance() {
      return defaultInstance;
    }
    
    public Book getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Book_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Book_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string isbn = 3;
    public static final int ISBN_FIELD_NUMBER = 3;
    private java.lang.Object isbn_;
    public boolean hasIsbn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getIsbn() {
      java.lang.Object ref = isbn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          isbn_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIsbnBytes() {
      java.lang.Object ref = isbn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        isbn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string author = 4;
    public static final int AUTHOR_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList author_;
    public java.util.List<String>
        getAuthorList() {
      return author_;
    }
    public int getAuthorCount() {
      return author_.size();
    }
    public String getAuthor(int index) {
      return author_.get(index);
    }
    
    // optional int64 publish_date = 5;
    public static final int PUBLISH_DATE_FIELD_NUMBER = 5;
    private long publishDate_;
    public boolean hasPublishDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getPublishDate() {
      return publishDate_;
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      isbn_ = "";
      author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      publishDate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIsbnBytes());
      }
      for (int i = 0; i < author_.size(); i++) {
        output.writeBytes(4, author_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, publishDate_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIsbnBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < author_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(author_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAuthorList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, publishDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.colorfuldays.ssm.domain.protobuf.Ssm.Book prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.colorfuldays.ssm.domain.protobuf.Ssm.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Book_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Book_fieldAccessorTable;
      }
      
      // Construct using org.colorfuldays.ssm.domain.protobuf.Ssm.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isbn_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        publishDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.Book.getDescriptor();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.Book getDefaultInstanceForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.Book.getDefaultInstance();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.Book build() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.colorfuldays.ssm.domain.protobuf.Ssm.Book buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.colorfuldays.ssm.domain.protobuf.Ssm.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.Book buildPartial() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.Book result = new org.colorfuldays.ssm.domain.protobuf.Ssm.Book(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isbn_ = isbn_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          author_ = new com.google.protobuf.UnmodifiableLazyStringList(
              author_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.publishDate_ = publishDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.colorfuldays.ssm.domain.protobuf.Ssm.Book) {
          return mergeFrom((org.colorfuldays.ssm.domain.protobuf.Ssm.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.colorfuldays.ssm.domain.protobuf.Ssm.Book other) {
        if (other == org.colorfuldays.ssm.domain.protobuf.Ssm.Book.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasIsbn()) {
          setIsbn(other.getIsbn());
        }
        if (!other.author_.isEmpty()) {
          if (author_.isEmpty()) {
            author_ = other.author_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAuthorIsMutable();
            author_.addAll(other.author_);
          }
          onChanged();
        }
        if (other.hasPublishDate()) {
          setPublishDate(other.getPublishDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              isbn_ = input.readBytes();
              break;
            }
            case 34: {
              ensureAuthorIsMutable();
              author_.add(input.readBytes());
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              publishDate_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string isbn = 3;
      private java.lang.Object isbn_ = "";
      public boolean hasIsbn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getIsbn() {
        java.lang.Object ref = isbn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          isbn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIsbn(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        isbn_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsbn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isbn_ = getDefaultInstance().getIsbn();
        onChanged();
        return this;
      }
      void setIsbn(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        isbn_ = value;
        onChanged();
      }
      
      // repeated string author = 4;
      private com.google.protobuf.LazyStringList author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAuthorIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          author_ = new com.google.protobuf.LazyStringArrayList(author_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getAuthorList() {
        return java.util.Collections.unmodifiableList(author_);
      }
      public int getAuthorCount() {
        return author_.size();
      }
      public String getAuthor(int index) {
        return author_.get(index);
      }
      public Builder setAuthor(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIsMutable();
        author_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addAuthor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIsMutable();
        author_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllAuthor(
          java.lang.Iterable<String> values) {
        ensureAuthorIsMutable();
        super.addAll(values, author_);
        onChanged();
        return this;
      }
      public Builder clearAuthor() {
        author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addAuthor(com.google.protobuf.ByteString value) {
        ensureAuthorIsMutable();
        author_.add(value);
        onChanged();
      }
      
      // optional int64 publish_date = 5;
      private long publishDate_ ;
      public boolean hasPublishDate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getPublishDate() {
        return publishDate_;
      }
      public Builder setPublishDate(long value) {
        bitField0_ |= 0x00000010;
        publishDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublishDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        publishDate_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.colorfuldays.ssm.domain.protobuf.Book)
    }
    
    static {
      defaultInstance = new Book(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.colorfuldays.ssm.domain.protobuf.Book)
  }
  
  public interface MapEntityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string key = 1;
    boolean hasKey();
    String getKey();
    
    // optional string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class MapEntity extends
      com.google.protobuf.GeneratedMessage
      implements MapEntityOrBuilder {
    // Use MapEntity.newBuilder() to construct.
    private MapEntity(Builder builder) {
      super(builder);
    }
    private MapEntity(boolean noInit) {}
    
    private static final MapEntity defaultInstance;
    public static MapEntity getDefaultInstance() {
      return defaultInstance;
    }
    
    public MapEntity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_fieldAccessorTable;
      }
      
      // Construct using org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.getDescriptor();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity getDefaultInstanceForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity build() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity buildPartial() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity result = new org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity) {
          return mergeFrom((org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity other) {
        if (other == org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // optional string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.colorfuldays.ssm.domain.protobuf.MapEntity)
    }
    
    static {
      defaultInstance = new MapEntity(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.colorfuldays.ssm.domain.protobuf.MapEntity)
  }
  
  public interface SessionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .org.colorfuldays.ssm.domain.protobuf.MapEntity attributes = 1;
    java.util.List<org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity> 
        getAttributesList();
    org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity getAttributes(int index);
    int getAttributesCount();
    java.util.List<? extends org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
        getAttributesOrBuilderList();
    org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder getAttributesOrBuilder(
        int index);
  }
  public static final class Session extends
      com.google.protobuf.GeneratedMessage
      implements SessionOrBuilder {
    // Use Session.newBuilder() to construct.
    private Session(Builder builder) {
      super(builder);
    }
    private Session(boolean noInit) {}
    
    private static final Session defaultInstance;
    public static Session getDefaultInstance() {
      return defaultInstance;
    }
    
    public Session getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Session_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Session_fieldAccessorTable;
    }
    
    // repeated .org.colorfuldays.ssm.domain.protobuf.MapEntity attributes = 1;
    public static final int ATTRIBUTES_FIELD_NUMBER = 1;
    private java.util.List<org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity> attributes_;
    public java.util.List<org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity> getAttributesList() {
      return attributes_;
    }
    public java.util.List<? extends org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    public int getAttributesCount() {
      return attributes_.size();
    }
    public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity getAttributes(int index) {
      return attributes_.get(index);
    }
    public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }
    
    private void initFields() {
      attributes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(1, attributes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attributes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.colorfuldays.ssm.domain.protobuf.Ssm.Session prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.colorfuldays.ssm.domain.protobuf.Ssm.SessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Session_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_Session_fieldAccessorTable;
      }
      
      // Construct using org.colorfuldays.ssm.domain.protobuf.Ssm.Session.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.Session.getDescriptor();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.Session getDefaultInstanceForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.Session.getDefaultInstance();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.Session build() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.Session result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.colorfuldays.ssm.domain.protobuf.Ssm.Session buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.colorfuldays.ssm.domain.protobuf.Ssm.Session result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.Session buildPartial() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.Session result = new org.colorfuldays.ssm.domain.protobuf.Ssm.Session(this);
        int from_bitField0_ = bitField0_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.colorfuldays.ssm.domain.protobuf.Ssm.Session) {
          return mergeFrom((org.colorfuldays.ssm.domain.protobuf.Ssm.Session)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.colorfuldays.ssm.domain.protobuf.Ssm.Session other) {
        if (other == org.colorfuldays.ssm.domain.protobuf.Ssm.Session.getDefaultInstance()) return this;
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder subBuilder = org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAttributes(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .org.colorfuldays.ssm.domain.protobuf.MapEntity attributes = 1;
      private java.util.List<org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          attributes_ = new java.util.ArrayList<org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity>(attributes_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> attributesBuilder_;
      
      public java.util.List<org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      public Builder setAttributes(
          int index, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAttributes(
          int index, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAttributes(org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAttributes(
          int index, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAttributes(
          org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAttributes(
          int index, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAttributes(
          java.lang.Iterable<? extends org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          super.addAll(values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance());
      }
      public org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance());
      }
      public java.util.List<org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder, org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntityOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.colorfuldays.ssm.domain.protobuf.Session)
    }
    
    static {
      defaultInstance = new Session(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.colorfuldays.ssm.domain.protobuf.Session)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_colorfuldays_ssm_domain_protobuf_Book_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_colorfuldays_ssm_domain_protobuf_Book_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_colorfuldays_ssm_domain_protobuf_Session_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_colorfuldays_ssm_domain_protobuf_Session_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tssm.proto\022$org.colorfuldays.ssm.domain" +
      ".protobuf\"2\n\004User\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 " +
      "\001(\t\022\020\n\010password\030\003 \001(\t\"T\n\004Book\022\n\n\002id\030\001 \001(" +
      "\003\022\014\n\004name\030\002 \001(\t\022\014\n\004isbn\030\003 \001(\t\022\016\n\006author\030" +
      "\004 \003(\t\022\024\n\014publish_date\030\005 \001(\003\"\'\n\tMapEntity" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"N\n\007Session\022" +
      "C\n\nattributes\030\001 \003(\0132/.org.colorfuldays.s" +
      "sm.domain.protobuf.MapEntityB&\n$org.colo" +
      "rfuldays.ssm.domain.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor,
              new java.lang.String[] { "Id", "Name", "Password", },
              org.colorfuldays.ssm.domain.protobuf.Ssm.User.class,
              org.colorfuldays.ssm.domain.protobuf.Ssm.User.Builder.class);
          internal_static_org_colorfuldays_ssm_domain_protobuf_Book_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_colorfuldays_ssm_domain_protobuf_Book_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_colorfuldays_ssm_domain_protobuf_Book_descriptor,
              new java.lang.String[] { "Id", "Name", "Isbn", "Author", "PublishDate", },
              org.colorfuldays.ssm.domain.protobuf.Ssm.Book.class,
              org.colorfuldays.ssm.domain.protobuf.Ssm.Book.Builder.class);
          internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_colorfuldays_ssm_domain_protobuf_MapEntity_descriptor,
              new java.lang.String[] { "Key", "Value", },
              org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.class,
              org.colorfuldays.ssm.domain.protobuf.Ssm.MapEntity.Builder.class);
          internal_static_org_colorfuldays_ssm_domain_protobuf_Session_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_org_colorfuldays_ssm_domain_protobuf_Session_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_colorfuldays_ssm_domain_protobuf_Session_descriptor,
              new java.lang.String[] { "Attributes", },
              org.colorfuldays.ssm.domain.protobuf.Ssm.Session.class,
              org.colorfuldays.ssm.domain.protobuf.Ssm.Session.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
