// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssm.proto

package org.colorfuldays.ssm.domain.protobuf;

public final class Ssm {
  private Ssm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string password = 3;
    boolean hasPassword();
    String getPassword();
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(Builder builder) {
      super(builder);
    }
    private User(boolean noInit) {}
    
    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.colorfuldays.ssm.domain.protobuf.Ssm.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.colorfuldays.ssm.domain.protobuf.Ssm.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable;
      }
      
      // Construct using org.colorfuldays.ssm.domain.protobuf.Ssm.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.User.getDescriptor();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.User getDefaultInstanceForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.User.getDefaultInstance();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.User build() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.colorfuldays.ssm.domain.protobuf.Ssm.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.colorfuldays.ssm.domain.protobuf.Ssm.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.User buildPartial() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.User result = new org.colorfuldays.ssm.domain.protobuf.Ssm.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.colorfuldays.ssm.domain.protobuf.Ssm.User) {
          return mergeFrom((org.colorfuldays.ssm.domain.protobuf.Ssm.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.colorfuldays.ssm.domain.protobuf.Ssm.User other) {
        if (other == org.colorfuldays.ssm.domain.protobuf.Ssm.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string password = 3;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.colorfuldays.ssm.domain.protobuf.User)
    }
    
    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.colorfuldays.ssm.domain.protobuf.User)
  }
  
  public interface bookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string isbn = 3;
    boolean hasIsbn();
    String getIsbn();
    
    // repeated string author = 4;
    java.util.List<String> getAuthorList();
    int getAuthorCount();
    String getAuthor(int index);
    
    // optional int64 publish_date = 5;
    boolean hasPublishDate();
    long getPublishDate();
  }
  public static final class book extends
      com.google.protobuf.GeneratedMessage
      implements bookOrBuilder {
    // Use book.newBuilder() to construct.
    private book(Builder builder) {
      super(builder);
    }
    private book(boolean noInit) {}
    
    private static final book defaultInstance;
    public static book getDefaultInstance() {
      return defaultInstance;
    }
    
    public book getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_book_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_book_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string isbn = 3;
    public static final int ISBN_FIELD_NUMBER = 3;
    private java.lang.Object isbn_;
    public boolean hasIsbn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getIsbn() {
      java.lang.Object ref = isbn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          isbn_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIsbnBytes() {
      java.lang.Object ref = isbn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        isbn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string author = 4;
    public static final int AUTHOR_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList author_;
    public java.util.List<String>
        getAuthorList() {
      return author_;
    }
    public int getAuthorCount() {
      return author_.size();
    }
    public String getAuthor(int index) {
      return author_.get(index);
    }
    
    // optional int64 publish_date = 5;
    public static final int PUBLISH_DATE_FIELD_NUMBER = 5;
    private long publishDate_;
    public boolean hasPublishDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getPublishDate() {
      return publishDate_;
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      isbn_ = "";
      author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      publishDate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIsbnBytes());
      }
      for (int i = 0; i < author_.size(); i++) {
        output.writeBytes(4, author_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, publishDate_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIsbnBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < author_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(author_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAuthorList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, publishDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.colorfuldays.ssm.domain.protobuf.Ssm.book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.colorfuldays.ssm.domain.protobuf.Ssm.book prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.colorfuldays.ssm.domain.protobuf.Ssm.bookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_book_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.internal_static_org_colorfuldays_ssm_domain_protobuf_book_fieldAccessorTable;
      }
      
      // Construct using org.colorfuldays.ssm.domain.protobuf.Ssm.book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isbn_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        publishDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.book.getDescriptor();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.book getDefaultInstanceForType() {
        return org.colorfuldays.ssm.domain.protobuf.Ssm.book.getDefaultInstance();
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.book build() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.colorfuldays.ssm.domain.protobuf.Ssm.book buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.colorfuldays.ssm.domain.protobuf.Ssm.book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.colorfuldays.ssm.domain.protobuf.Ssm.book buildPartial() {
        org.colorfuldays.ssm.domain.protobuf.Ssm.book result = new org.colorfuldays.ssm.domain.protobuf.Ssm.book(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isbn_ = isbn_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          author_ = new com.google.protobuf.UnmodifiableLazyStringList(
              author_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.publishDate_ = publishDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.colorfuldays.ssm.domain.protobuf.Ssm.book) {
          return mergeFrom((org.colorfuldays.ssm.domain.protobuf.Ssm.book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.colorfuldays.ssm.domain.protobuf.Ssm.book other) {
        if (other == org.colorfuldays.ssm.domain.protobuf.Ssm.book.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasIsbn()) {
          setIsbn(other.getIsbn());
        }
        if (!other.author_.isEmpty()) {
          if (author_.isEmpty()) {
            author_ = other.author_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAuthorIsMutable();
            author_.addAll(other.author_);
          }
          onChanged();
        }
        if (other.hasPublishDate()) {
          setPublishDate(other.getPublishDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              isbn_ = input.readBytes();
              break;
            }
            case 34: {
              ensureAuthorIsMutable();
              author_.add(input.readBytes());
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              publishDate_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string isbn = 3;
      private java.lang.Object isbn_ = "";
      public boolean hasIsbn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getIsbn() {
        java.lang.Object ref = isbn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          isbn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIsbn(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        isbn_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsbn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isbn_ = getDefaultInstance().getIsbn();
        onChanged();
        return this;
      }
      void setIsbn(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        isbn_ = value;
        onChanged();
      }
      
      // repeated string author = 4;
      private com.google.protobuf.LazyStringList author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAuthorIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          author_ = new com.google.protobuf.LazyStringArrayList(author_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getAuthorList() {
        return java.util.Collections.unmodifiableList(author_);
      }
      public int getAuthorCount() {
        return author_.size();
      }
      public String getAuthor(int index) {
        return author_.get(index);
      }
      public Builder setAuthor(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIsMutable();
        author_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addAuthor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIsMutable();
        author_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllAuthor(
          java.lang.Iterable<String> values) {
        ensureAuthorIsMutable();
        super.addAll(values, author_);
        onChanged();
        return this;
      }
      public Builder clearAuthor() {
        author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addAuthor(com.google.protobuf.ByteString value) {
        ensureAuthorIsMutable();
        author_.add(value);
        onChanged();
      }
      
      // optional int64 publish_date = 5;
      private long publishDate_ ;
      public boolean hasPublishDate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getPublishDate() {
        return publishDate_;
      }
      public Builder setPublishDate(long value) {
        bitField0_ |= 0x00000010;
        publishDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublishDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        publishDate_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.colorfuldays.ssm.domain.protobuf.book)
    }
    
    static {
      defaultInstance = new book(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.colorfuldays.ssm.domain.protobuf.book)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_colorfuldays_ssm_domain_protobuf_book_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_colorfuldays_ssm_domain_protobuf_book_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tssm.proto\022$org.colorfuldays.ssm.domain" +
      ".protobuf\"2\n\004User\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 " +
      "\001(\t\022\020\n\010password\030\003 \001(\t\"T\n\004book\022\n\n\002id\030\001 \001(" +
      "\003\022\014\n\004name\030\002 \001(\t\022\014\n\004isbn\030\003 \001(\t\022\016\n\006author\030" +
      "\004 \003(\t\022\024\n\014publish_date\030\005 \001(\003B&\n$org.color" +
      "fuldays.ssm.domain.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_colorfuldays_ssm_domain_protobuf_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_colorfuldays_ssm_domain_protobuf_User_descriptor,
              new java.lang.String[] { "Id", "Name", "Password", },
              org.colorfuldays.ssm.domain.protobuf.Ssm.User.class,
              org.colorfuldays.ssm.domain.protobuf.Ssm.User.Builder.class);
          internal_static_org_colorfuldays_ssm_domain_protobuf_book_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_colorfuldays_ssm_domain_protobuf_book_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_colorfuldays_ssm_domain_protobuf_book_descriptor,
              new java.lang.String[] { "Id", "Name", "Isbn", "Author", "PublishDate", },
              org.colorfuldays.ssm.domain.protobuf.Ssm.book.class,
              org.colorfuldays.ssm.domain.protobuf.Ssm.book.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
